### ISSUE TITLE
Build Error from following build instructions in README

### ISSUE THREAD

**Issue by seventhplacedad** [jgarzik/rust-protobuf-example#3]
`cargo build` 

```
  Compiling rust-protobuf-example v1.0.1 (/home/kevlar/rust-protobuf-example)
error: failed to run custom build command for `rust-protobuf-example v1.0.1 (/home/kevlar/rust-protobuf-example)`

Caused by:
  process didn't exit successfully: `/home/kevlar/rust-protobuf-example/target/debug/build/rust-protobuf-example-c10fd022b491d154/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', /home/kevlar/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-2.27.1/src/lib.rs:209:17
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
     2: protoc::Protoc::from_env_path
               at /home/kevlar/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-2.27.1/src/lib.rs:209:17
     3: protoc_rust::Codegen::run
               at /home/kevlar/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-rust-2.27.1/src/lib.rs:173:21
     4: protoc_rust::run
               at /home/kevlar/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-rust-2.27.1/src/lib.rs:237:5
     5: build_script_build::main
               at ./build.rs:6:2
     6: core::ops::function::FnOnce::call_once
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by seventhplacedad** [comment]
Unclear how this fixes the issue, but my build error was solved by installing protoc.

ie 

`sudo apt install protobuf-compiler`
